import { useCallback, useEffect, useState } from "react"
import { Pencil, Plus, Search, Trash2 } from "lucide-react"
import { customerService } from "@/services/apiServices"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Modal } from "@/components/Modal"
import { EmptyState, ErrorMessage, LoadingState } from "@/components/PageStates"
import { Pagination } from "@/components/Pagination"
import { useToast } from "@/hooks/useToast"

const emptyCustomer = () => ({ name: "", email: "", phone: "", address: "" })
export function CustomersPage() {
  const toast = useToast()
  const [result, setResult] = useState(null), [page, setPage] = useState(1), [search, setSearch] = useState(""), [loading, setLoading] = useState(true), [error, setError] = useState("")
  const [open, setOpen] = useState(false), [editing, setEditing] = useState(null), [form, setForm] = useState(emptyCustomer), [saving, setSaving] = useState(false)
  const load = useCallback(async () => { setLoading(true); setError(""); try { setResult(await customerService.list({ page, search, per_page: 10 })) } catch (e) { setError(e.message) } finally { setLoading(false) } }, [page, search])
  useEffect(() => { const id = setTimeout(load, 250); return () => clearTimeout(id) }, [load])
  function openForm(item = null) { setEditing(item); setForm(item ? { name: item.name, email: item.email ?? "", phone: item.phone ?? "", address: item.address ?? "" } : emptyCustomer()); setError(""); setOpen(true) }
  async function submit(e) { e.preventDefault(); setSaving(true); setError(""); try { const action = editing ? "updated" : "created"; editing ? await customerService.update(editing.id, form) : await customerService.create(form); toast.success(`Customer ${action} successfully.`); setOpen(false); await load() } catch (err) { setError(err.message); toast.error(err.message, "Could not save customer") } finally { setSaving(false) } }
  async function remove(item) { if (!window.confirm(`Delete ${item.name}? Existing orders will become walk-in orders.`)) return; try { await customerService.remove(item.id); toast.success(`${item.name} was deleted.`); await load() } catch (e) { setError(e.message); toast.error(e.message, "Could not delete customer") } }
  return <div className="mx-auto max-w-6xl space-y-5"><div className="flex justify-between gap-3"><div><h1 className="text-3xl font-bold">Customers</h1><p className="mt-1 text-zinc-500">Maintain customer contact details.</p></div><Button onClick={() => openForm()}><Plus size={17}/>Add customer</Button></div><Card className="p-5"><div className="relative mb-5 max-w-md"><Search className="absolute left-3 top-2.5 text-zinc-400" size={19}/><Input className="pl-10" placeholder="Search customers…" value={search} onChange={(e) => { setSearch(e.target.value); setPage(1) }}/></div><ErrorMessage message={error}/>{loading ? <LoadingState/> : !result?.data.length ? <EmptyState/> : <><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-zinc-500"><tr><th className="pb-3">Name</th><th className="pb-3">Email</th><th className="pb-3">Phone</th><th className="pb-3">Address</th><th className="pb-3 text-right">Actions</th></tr></thead><tbody>{result.data.map((item) => <tr key={item.id} className="border-b border-zinc-100"><td className="py-4 font-semibold">{item.name}</td><td className="py-4">{item.email || "—"}</td><td className="py-4">{item.phone || "—"}</td><td className="max-w-52 truncate py-4 text-zinc-500">{item.address || "—"}</td><td className="py-4"><div className="flex justify-end"><Button variant="ghost" size="icon" onClick={() => openForm(item)}><Pencil size={16}/></Button><Button variant="ghost" size="icon" onClick={() => remove(item)}><Trash2 size={16}/></Button></div></td></tr>)}</tbody></table></div><Pagination meta={result} onPageChange={setPage}/></>}</Card><Modal title={editing ? "Edit customer" : "Add customer"} open={open} onClose={() => setOpen(false)}><form className="space-y-4" onSubmit={submit}><ErrorMessage message={error}/>{[["Name","name","text"],["Email","email","email"],["Phone","phone","tel"]].map(([label,key,type]) => <label key={key} className="block text-sm font-medium">{label}<Input className="mt-1" type={type} value={form[key]} required={key === "name"} onChange={(e) => setForm({ ...form, [key]: e.target.value })}/></label>)}<label className="block text-sm font-medium">Address<textarea className="mt-1 min-h-20 w-full rounded-lg border border-zinc-200 p-3 text-sm" value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })}/></label><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button disabled={saving}>{saving ? "Saving…" : "Save customer"}</Button></div></form></Modal></div>
}
