import { useCallback, useEffect, useState } from "react"
import { Printer as Eye, XCircle } from "lucide-react"
import { orderService } from "@/services/apiServices"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Modal } from "@/components/Modal"
import { EmptyState, ErrorMessage, LoadingState } from "@/components/PageStates"
import { Pagination } from "@/components/Pagination"
import { useToast } from "@/hooks/useToast"

export function OrdersPage() {
  const toast = useToast()
  const [result, setResult] = useState(null), [page, setPage] = useState(1), [status, setStatus] = useState(""), [loading, setLoading] = useState(true), [error, setError] = useState(""), [selected, setSelected] = useState(null)
  const load = useCallback(async () => { setLoading(true); setError(""); try { setResult(await orderService.list({ page, status, per_page: 10 })) } catch (e) { setError(e.message) } finally { setLoading(false) } }, [page, status])
  useEffect(() => { const id = setTimeout(load, 0); return () => clearTimeout(id) }, [load])
  function view(id) { window.open(`/orders/${id}/invoice`, "_blank", "noopener,noreferrer") }
  async function cancel(order) { if (!window.confirm(`Cancel ${order.order_number} and restore its stock?`)) return; try { await orderService.cancel(order.id); toast.success(`${order.order_number} cancelled and stock restored.`); setSelected(null); await load() } catch (e) { setError(e.message); toast.error(e.message, "Could not cancel order") } }
  return <div className="mx-auto max-w-7xl space-y-5"><div><h1 className="text-3xl font-bold">Orders</h1><p className="mt-1 text-zinc-500">Review transactions and cancel orders when needed.</p></div><Card className="p-5"><select className="mb-5 h-10 rounded-lg border border-zinc-200 bg-white px-3 text-sm" value={status} onChange={(e) => { setStatus(e.target.value); setPage(1) }}><option value="">All statuses</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select><ErrorMessage message={error}/>{loading ? <LoadingState/> : !result?.data.length ? <EmptyState/> : <><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-zinc-500"><tr><th className="pb-3">Order</th><th className="pb-3">Customer</th><th className="pb-3">Items</th><th className="pb-3">Payment</th><th className="pb-3">Total</th><th className="pb-3">Status</th><th className="pb-3 text-right">Actions</th></tr></thead><tbody>{result.data.map((o) => <tr key={o.id} className="border-b border-zinc-100"><td className="py-4"><p className="font-semibold">{o.order_number}</p><p className="text-xs text-zinc-500">{new Date(o.ordered_at).toLocaleString()}</p></td><td>{o.customer?.name ?? "Walk-in"}</td><td>{o.items_count}</td><td className="uppercase">{o.payment_method}</td><td className="font-bold">${Number(o.total).toFixed(2)}</td><td><span className={`rounded-full px-2 py-1 text-xs capitalize ${o.status === "completed" ? "bg-emerald-100 text-emerald-700" : "bg-red-100 text-red-700"}`}>{o.status}</span></td><td><div className="flex justify-end"><Button variant="ghost" size="icon" onClick={() => view(o.id)}><Eye size={16}/></Button>{o.status !== "cancelled" && <Button variant="ghost" size="icon" onClick={() => cancel(o)}><XCircle size={16}/></Button>}</div></td></tr>)}</tbody></table></div><Pagination meta={result} onPageChange={setPage}/></>}</Card>
    <Modal title={selected?.order_number ?? "Order details"} open={Boolean(selected)} onClose={() => setSelected(null)}><div className="space-y-4">{selected && <><div className="grid grid-cols-2 gap-3 rounded-xl bg-zinc-50 p-4 text-sm"><div><p className="text-zinc-500">Customer</p><p className="font-semibold">{selected.customer?.name ?? "Walk-in"}</p></div><div><p className="text-zinc-500">Payment</p><p className="font-semibold uppercase">{selected.payment_method}</p></div></div><div>{selected.items.map((i) => <div key={i.id} className="flex justify-between border-b py-2 text-sm"><div><p className="font-medium">{i.product_name}</p><p className="text-zinc-500">{i.quantity} × ${Number(i.unit_price).toFixed(2)}</p></div><p className="font-semibold">${Number(i.line_total).toFixed(2)}</p></div>)}</div><div className="space-y-1 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>${Number(selected.subtotal).toFixed(2)}</span></div><div className="flex justify-between"><span>Tax</span><span>${Number(selected.tax).toFixed(2)}</span></div><div className="flex justify-between text-lg font-bold"><span>Total</span><span>${Number(selected.total).toFixed(2)}</span></div></div>{selected.status !== "cancelled" && <Button variant="outline" className="w-full text-red-600" onClick={() => cancel(selected)}>Cancel order</Button>}</>}</div></Modal>
  </div>
}
