import { useCallback, useEffect, useState } from "react"
import { Pencil, Plus, Search, Trash2 } from "lucide-react"
import { categoryService, productService } from "@/services/apiServices"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Modal } from "@/components/Modal"
import { EmptyState, ErrorMessage, LoadingState } from "@/components/PageStates"
import { Pagination } from "@/components/Pagination"
import { useToast } from "@/hooks/useToast"

const emptyProduct = () => ({ category_id: "", name: "", sku: "", description: "", price: "", cost: 0, stock: 0, emoji: "📦", image: "", is_active: true })

export function ProductsPage() {
  const toast = useToast()
  const [result, setResult] = useState(null), [categories, setCategories] = useState([]), [page, setPage] = useState(1), [search, setSearch] = useState(""), [categoryId, setCategoryId] = useState("")
  const [loading, setLoading] = useState(true), [error, setError] = useState(""), [open, setOpen] = useState(false), [editing, setEditing] = useState(null), [form, setForm] = useState(emptyProduct), [saving, setSaving] = useState(false)
  const load = useCallback(async () => { setLoading(true); setError(""); try { setResult(await productService.list({ page, search, category_id: categoryId, per_page: 10 })) } catch (e) { setError(e.message) } finally { setLoading(false) } }, [page, search, categoryId])
  useEffect(() => { categoryService.list({ per_page: 100 }).then((r) => setCategories(r.data)).catch((e) => setError(e.message)) }, [])
  useEffect(() => { const id = setTimeout(load, 250); return () => clearTimeout(id) }, [load])
  function openForm(item = null) { setEditing(item); setForm(item ? { category_id: item.category_id, name: item.name, sku: item.sku, description: item.description ?? "", price: item.price, cost: item.cost, stock: item.stock, emoji: item.emoji ?? "📦", image: item.image ?? "", is_active: item.is_active } : emptyProduct()); setError(""); setOpen(true) }
  async function submit(event) { event.preventDefault(); setSaving(true); setError(""); try { const action = editing ? "updated" : "created"; editing ? await productService.update(editing.id, form) : await productService.create(form); toast.success(`Product ${action} successfully.`); setOpen(false); await load() } catch (e) { setError(e.message); toast.error(e.message, "Could not save product") } finally { setSaving(false) } }
  async function remove(item) { if (!window.confirm(`Delete ${item.name}?`)) return; try { await productService.remove(item.id); toast.success(`${item.name} was deleted.`); await load() } catch (e) { setError(e.message); toast.error(e.message, "Could not delete product") } }
  return <div className="mx-auto max-w-7xl space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-bold">Products</h1><p className="mt-1 text-zinc-500">Manage pricing, inventory, and availability.</p></div><Button onClick={() => openForm()}><Plus size={17}/>Add product</Button></div>
    <Card className="p-5"><div className="mb-5 flex flex-wrap gap-3"><div className="relative min-w-64 flex-1"><Search className="absolute left-3 top-2.5 text-zinc-400" size={19}/><Input className="pl-10" placeholder="Search name or SKU…" value={search} onChange={(e) => { setSearch(e.target.value); setPage(1) }}/></div><select className="h-10 rounded-lg border border-zinc-200 bg-white px-3 text-sm" value={categoryId} onChange={(e) => { setCategoryId(e.target.value); setPage(1) }}><option value="">All categories</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></div><ErrorMessage message={error}/>{loading ? <LoadingState/> : !result?.data.length ? <EmptyState/> : <><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-zinc-500"><tr><th className="pb-3">Product</th><th className="pb-3">SKU</th><th className="pb-3">Category</th><th className="pb-3">Price</th><th className="pb-3">Stock</th><th className="pb-3">Status</th><th className="pb-3 text-right">Actions</th></tr></thead><tbody>{result.data.map((item) => <tr key={item.id} className="border-b border-zinc-100"><td className="py-4"><span className="mr-2 text-xl">{item.emoji}</span><span className="font-semibold">{item.name}</span></td><td className="py-4 text-zinc-500">{item.sku}</td><td className="py-4">{item.category?.name}</td><td className="py-4 font-semibold">${Number(item.price).toFixed(2)}</td><td className={`py-4 ${item.stock <= 10 ? "font-semibold text-amber-700" : ""}`}>{item.stock}</td><td className="py-4">{item.is_active ? "Active" : "Inactive"}</td><td className="py-4"><div className="flex justify-end"><Button variant="ghost" size="icon" onClick={() => openForm(item)}><Pencil size={16}/></Button><Button variant="ghost" size="icon" onClick={() => remove(item)}><Trash2 size={16}/></Button></div></td></tr>)}</tbody></table></div><Pagination meta={result} onPageChange={setPage}/></>}</Card>
    <Modal title={editing ? "Edit product" : "Add product"} open={open} onClose={() => setOpen(false)} wide><form className="grid gap-4 sm:grid-cols-2" onSubmit={submit}><div className="sm:col-span-2"><ErrorMessage message={error}/></div>{[["Name","name","text"],["SKU","sku","text"],["Price","price","number"],["Cost","cost","number"],["Stock","stock","number"],["Emoji","emoji","text"]].map(([label,key,type]) => <label key={key} className="block text-sm font-medium">{label}<Input className="mt-1" type={type} step={key === "price" || key === "cost" ? "0.01" : undefined} min={type === "number" ? 0 : undefined} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} required={["name","sku","price"].includes(key)}/></label>)}<label className="block text-sm font-medium sm:col-span-2">Category<select className="mt-1 h-10 w-full rounded-lg border border-zinc-200 bg-white px-3 text-sm" value={form.category_id} onChange={(e) => setForm({ ...form, category_id: e.target.value })} required><option value="">Choose category</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="block text-sm font-medium sm:col-span-2">Description<textarea className="mt-1 min-h-20 w-full rounded-lg border border-zinc-200 p-3 text-sm" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })}/></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.is_active} onChange={(e) => setForm({ ...form, is_active: e.target.checked })}/>Active</label><div className="flex justify-end gap-2 sm:col-span-2"><Button type="button" variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button disabled={saving}>{saving ? "Saving…" : "Save product"}</Button></div></form></Modal>
  </div>
}
